### ISSUE TITLE
[REMOTE] Allow users to securely pass their kubeconfig to the nf-api container at runtime, not just at creation

### ISSUE THREAD

**Issue by cbmckni** [SciDAS/nextflow-api#17]
Users should be able to pass in their kubeconfig to Nextflow-API while the server is running, not just at creation. A secure way of doing this must be established. 

This will involve creating a new API call and encryption backend.

Mozilla SOPS might be a possible solution

**Comment by bentsherman** [comment]
Closing, refer to the discussion in #16.
