### ISSUE TITLE
[REMOTE] Use the remote cluster's PVCs with buses to provide persistent storage of workflow metadata(eliminate need for host PVC)

### ISSUE THREAD

**Issue by cbmckni** [SciDAS/nextflow-api#18]
To eliminate the need for a PVC on the host K8s cluster, Nextflow-API should store workflow data on remote clusters. 

Nextflow-API will update changes to this data through a secure bus.

Possible technologies:

https://www.rabbitmq.com/ or http://mqtt.org/ --> bus mechanisms

https://redis.io/topics/pubsub as well

other tools that are useful for log manipulation but maybe not the soln for this problem are https://fluentbit.io/  and  https://www.elastic.co/products/logstash

https://www.amqp.org/  is the protocol

**Comment by bentsherman** [comment]
Closing, refer to the discussion in #16.
