### ISSUE TITLE
[REMOTE] Authenticate access to remote clusters with service accounts instead of kubeconfigs(tokens frequently expire, leading to frequent re-downloads/headaches)

### ISSUE THREAD

**Issue by cbmckni** [SciDAS/nextflow-api#19]
Users should only need to submit authentication info once for each remote cluster. 

As kubeconfig security tokens expire, service accounts should instead be used, as server-server communication is what they are designed for.

Nextflow-API should be configured to use service accounts on external clusters, as an option

**Comment by bentsherman** [comment]
Closing, refer to the discussion in #16.
