### ISSUE TITLE
Remove old deployment files, just use helm

### ISSUE THREAD

**Issue by bentsherman** [SciDAS/nextflow-api#25]
Currently there are multiple copies of deployment files in the repo, but I think we should use the helm files exclusively. We just need to make sure the helm files are completely up date, that they work for both PRP and GKE, and that their usage instructions are complete, including installing helm.

**Comment by cbmckni** [comment]
https://github.com/SciDAS/nextflow-api/pull/30

**Comment by bentsherman** [comment]
Done.
