### ISSUE TITLE
Workflow status is not updated on completion / failure

### ISSUE THREAD

**Issue by bentsherman** [SciDAS/nextflow-api#39]
On the pre-release PR, when a workflow completes or fails, the status is not updated in the workflow view, it still just says "running".

I have been testing locally with the `rnatoy` and `hello` workflows since they run out of the box and finish quickly. So far I have confirmed (with print statements) that the workflow does make it all the way through the `launch_async` function, it does not seem to get hung on any of the async funtions that it calls.

However I noticed that if I run a workflow, wait for it to finish, then kill the server and restart it, the status immediately updates on the webpage. I think the workflow status is being updated correctly but for some reason it doesn't get served correctly, as if the server is caching old results.

@cbmckni can you reproduce this on your local machine and see what you think?

**Comment by bentsherman** [comment]
Small update: my observation above was with the json backend. With the mongo backend, the workflow status does not get updated and in fact I think the `launch_async` function does not even finish. That may be the result of a separate issue.

**Comment by cbmckni** [comment]
It fails to update with the json backend. Here's how I deploy. Are you doing anything different?
```
$docker run -p 127.0.0.1:8080:8080 -i -t cbmckni/nextflow-api /bin/bash
root@98caeaebb67f:/opt/nextflow-api# cd /opt/nextflow-api; python3 bin/server.py --backend=json
The API is listening on http://0.0.0.0:8080
```

**Comment by bentsherman** [comment]
I'm not using docker but I would expect the behavior to be the same. If I kill the server and restart then I see the status updated.

**Comment by bentsherman** [comment]
Looking a bit deeper, I did this test again with both backends and checked the backend data. For mongo, the status was not updated in the mongo collection. For json, the status was updated in the json file. So I think I just need to fix this other issue with mongo and forking, and then we need to see if tornado is caching the response for the log endpoint.

**Comment by bentsherman** [comment]
Now that I fixed the other problem with mongo, the mongo backend also handles the status correctly.  So I think the actual issue now is specific to the json backend. Whenever a workflow is launched in a separate process, the json backend is also copied, so any updates made in the launch process are temporarily lost. They are saved to the json file, but the original backend copy never re-loads the json file so it doesn't see those updates... unless you restart the server.

So we need to refactor the json backend slightly to work across multiple processes...

**Comment by bentsherman** [comment]
I was able to fix this problem for the json backend as well. The json backend should now be _mostly_ thread-safe but I would not use it for large production runs. It is really only intended as a duct-tape alternative for when mongo is not available.

**Comment by bentsherman** [comment]
This issue is still happening, and I think it has something to do with nextflow kuberun. I only tested with the local executor so I need to test with kuberun to figure out the cause.

**Comment by bentsherman** [comment]
After a bit more testing on Nautilus, it seems like the workflow status is updated correctly... sometimes. I'm not sure yet if it's random, or if it only works for certain pipelines, or if it only works the first few times after server init. The print statements in `launch_async` don't print until the very end when they all get flushed at once, so if the function doesn't make it to the end for whatever reason, none of the debug messages are printed.

At this point Nextflow-API is totally usable. The downside with this issue is that the status won't always update correctly, and usually in that case the archive of output data is never created, although the individual output files are available.

There might be something I'm doing wrong with Python/Tornado, or maybe we're just trying to do something that isn't fully supported. If it becomes a big deal and we can't find a solution, I think it would be better to re-implement Nextflow-API in NodeJS which has much better support for asynchronous computing. I have a feeling that the Python GIL is just always going to hinder us here.

**Comment by bentsherman** [comment]
Small update, it seems like for workflows that complete successfully do create the output archive and update their status... eventually. Sometimes it just takes longer. It could be because nextflow kuberun probably doesn't actually exit until it's workflow pod is terminated. For workflows that fail I'm not sure yet because there are many ways a workflow can fail and while `launch_async` should handle all failures the same way, I'm not convinced yet that it does.

**Comment by cbmckni** [comment]
Should we just remove the status feature entirely? It's an obvious bug that really doesn't change the user experience in a particularly meaningful way....

Users can still check the status of their workflow through the logs.

**Comment by bentsherman** [comment]
I'm not going to remove it just yet, because I think I might be able to use the incoming tasks to tell when a workflow is done. In other words, nextflow sends a "completed" task or "failed" task when the entire workflow completes or fails. So we could have nextflow-api update the status when that message comes in.

**Comment by bentsherman** [comment]
Okay I was able to implement my idea with the tasks and I think it is working a lot better. @cbmckni feel free to experiment more and let me know how it goes.

**Comment by bentsherman** [comment]
It works!
